[c/fr] C French translation
adambard/learnxinyminutes-docs pull request #3972
Opened 2020-07-15 14:11 UTC by sun-exploit

New C French translation c-fr.html.markdown file

- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

2020-09-09 15:09 UTC, zethis commented
Nice to have !

2020-09-29 13:06 UTC, vendethiel requested changes

2020-09-29 13:06 UTC, vendethiel commented on fr-fr/c-fr.html.markdown
> +  // sizeof(obj) revoie la taille en sortie de l'expression (variable, literal, etc.).
"literal"

la version non-type est `sizeof obj`

2020-09-29 13:06 UTC, vendethiel commented on fr-fr/c-fr.html.markdown
> +  // Si l'argument de l'opérateur `sizeof` est une expression, alors son argument
à la différence de quel autre cas ... ?

2020-09-29 13:06 UTC, vendethiel commented on fr-fr/c-fr.html.markdown
> +Exemple: inversion sur place d'une chaîne de caractères
espace avant `:`

2020-09-29 13:06 UTC, vendethiel commented on fr-fr/c-fr.html.markdown
> +// Une fonction void retourne aucune valeur
*ne retourne

2020-09-29 13:06 UTC, vendethiel commented on fr-fr/c-fr.html.markdown
> +At run time, functions are located at known memory addresses. Function pointers are
(La version non traduite n'a pas été supprimée)

2020-09-29 13:06 UTC, vendethiel commented on fr-fr/c-fr.html.markdown
> +des inexactitudes (enfin, des idées qui ne sont plus considérées comme bonnes) ou des pratiques désormais modifiées.
alors pourquoi est-ce *le* livre ?

je suppose encore que c'est dans le fichier de base.

2024-04-04 11:58 UTC, verhovsky commented
@vendethiel can you make the edits yourself and merge this please? You can do it from the browser if you click here

<img width="1280" alt="editfile" src="https://github.com/adambard/learnxinyminutes-docs/assets/5687998/1f25e261-e306-4b73-bb41-7730e410594a">

2024-04-12 11:15 UTC, merged

2024-04-12 11:16 UTC, vendethiel commented
I think parts of this may have been machine translated. Fixed what I could and merged!