[wolfram/zh-cn]Create wolfram-cn.html.markdown
adambard/learnxinyminutes-docs pull request #4002
Opened 2020-08-20 18:47 UTC by wuyudi

- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]`
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

2020-10-20 11:20 UTC, imba-tjd requested changes

2020-10-20 11:20 UTC, imba-tjd commented on zh-cn/wolfram-cn.html.markdown
> +(* 这是一个评论 *)
```suggestion
(* 这是一个注释 *)
```

2020-10-20 11:20 UTC, imba-tjd commented on zh-cn/wolfram-cn.html.markdown
> +filename: learnwolfram.nb
```suggestion
filename: learnwolfram-cn.nb
```

2020-10-20 11:20 UTC, imba-tjd commented on zh-cn/wolfram-cn.html.markdown
> +myHash[["Puce"]] := 3.5                 (* 3.5, 拓展它 *)
```suggestion
myHash[["Green"]]                       (* 2, 使用 *)
myHash[["Green"]] := 5                  (* 5, 更新 *)
myHash[["Puce"]] := 3.5                 (* 3.5, 扩展 *)
```

2020-10-20 11:20 UTC, imba-tjd commented on zh-cn/wolfram-cn.html.markdown
> +(* 如果 和 条件 *)
```suggestion
(* If 和 条件 *)
```

2020-10-20 11:20 UTC, imba-tjd commented on zh-cn/wolfram-cn.html.markdown
> +x = 8; If[x==8, Print@"Yes", Print@"No"]   (* 条件，返回真的情况下，否则 *)
我觉得还不如不翻

2020-10-21 08:15 UTC, wuyudi commented on zh-cn/wolfram-cn.html.markdown
> +x = 8; If[x==8, Print@"Yes", Print@"No"]   (* 条件，返回真的情况下，否则 *)
fixed

2021-08-08 04:57 UTC, imba-tjd approved these changes

2021-08-08 05:06 UTC, imba-tjd commented
Hi，方便把后五条提交rebase成一条然后force push吗？如果不行也没关系。

2021-08-08 07:30 UTC, wuyudi commented
solved.

2021-08-08 08:42 UTC, merged

2021-08-08 08:43 UTC, imba-tjd commented
OK, Thank you!