Update set-theory.html.markdown
adambard/learnxinyminutes-docs pull request #4168
Opened 2021-05-23 05:41 UTC by kieutrang1729

Fixed a minor typo.

- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

2021-06-09 11:20 UTC, kieutrang1729 commented
Hi @vendethiel, can you review this?

2021-07-03 18:57 UTC, vendethiel requested changes
Désolé du délai. Merci pour la PR !

2021-07-03 18:57 UTC, vendethiel commented on fr-fr/set-theory-fr.html.markdown
> +2. Il n'y a pas d'accord général sur l'appartenance de zéro dans l'ensemble des nombres naturels, et les livres indiquent explicitment si l'auteur considere le zéro comme nombre naturel ou pas.
considère

2021-07-03 18:57 UTC, vendethiel commented on fr-fr/set-theory-fr.html.markdown
> +* L'ensemble vide peut se définir en comprehension à l'aide d'une propriété qui est satisfait par nul élément, e.g. `∅ = { x : x ≠ x }`, ou `∅ = { x : x ∈ N, x < 0 }`;
n'est satisfaite

2021-07-03 18:57 UTC, vendethiel commented on fr-fr/set-theory-fr.html.markdown
> +* il n'y a q'un seul ensemble vide;
qu'un

2021-07-03 18:57 UTC, vendethiel commented on fr-fr/set-theory-fr.html.markdown
> +* la cardinalité de l'ensemble vide est 0, i.e. `|∅| = 0`.
peut-être changer "i.e." par "ou" ?

2021-07-03 18:57 UTC, vendethiel commented on fr-fr/set-theory-fr.html.markdown
> +Un ensemble peut être defini en extension par une liste de tous les éléments qui sont contenu dans l'ensemble. Par exemple, `S = { a, b, c, d }`.
contenus

2021-07-03 18:57 UTC, vendethiel commented on fr-fr/set-theory-fr.html.markdown
> +* Un élément ne peut apparaître q'au plus une seule fois - il n'y a jamais de répétition, e.g. `{ 1, 2, 2, 3, 4, 3, 4, 2 } = { 1, 2, 3, 4 }`.
qu'au

2021-07-03 18:57 UTC, vendethiel commented on fr-fr/set-theory-fr.html.markdown
> +* Les ensembles n'ont pas de notion d'ordre, e.g. `{ 1, 2, 3, 4 } = { 2, 3, 1, 4 }`.
pareil que pour "i.e.", je ne vois pas "e.g." très souvent utilisé en français. Peut-être préférer un simple "par exemple" ?

2021-07-03 18:57 UTC, vendethiel commented on fr-fr/set-theory-fr.html.markdown
> +Le différence de deux ensembles `A` et `B` est l'ensemble contenant tous les éléments de l'ensemble `A` qui n'appartient pas à `B`.
La

2021-07-10 20:03 UTC, kieutrang1729 commented on fr-fr/set-theory-fr.html.markdown
> +* l'opérateur différence, `\`, signifie "sans", (lire "A moins B");
Pourquoi l'espace avant le point-virgule?

2021-07-10 20:05 UTC, kieutrang1729 commented
Je suis nouveau à github, et si j'ai fait quelque chose de bête, je te prie de me le dire!

2021-07-11 01:57 UTC, vendethiel commented on fr-fr/set-theory-fr.html.markdown
> +* l'opérateur différence, `\`, signifie "sans", (lire "A moins B");
C’est la règle en français

2021-07-11 12:29 UTC, kieutrang1729 commented on fr-fr/set-theory-fr.html.markdown
> +* l'opérateur différence, `\`, signifie "sans", (lire "A moins B");
OK, merci. Je les ai tous corrigés.

2021-07-11 14:28 UTC, vendethiel approved these changes

2021-07-11 14:28 UTC, vendethiel commented
Merci :)

2021-07-11 14:28 UTC, merged