[Easylang/en] Add Easylang
adambard/learnxinyminutes-docs pull request #4236
Opened 2021-09-27 17:57 UTC by chkas

- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

2021-11-02 14:53 UTC, Menelion requested changes
Thank you. Please review comments then I'll merge.

2021-11-02 14:53 UTC, Menelion commented on easylang.html.markdown
> +# input" reads a string from the "input_data" section,
`"input"`

2021-11-02 19:32 UTC, chkas commented on easylang.html.markdown
> +# input" reads a string from the "input_data" section,
Thank you. Well seen.

2021-11-02 19:46 UTC, chkas commented
Thank you for reviewing. Do I need to do anything more?

2021-11-02 19:46 UTC, closed without merging

2021-11-02 19:52 UTC, chkas commented
I am not so skilled with Github. Was the close now a mistake.

2021-11-03 13:48 UTC, chkas commented on easylang.html.markdown
> +---
filename: easylang.el

2021-11-03 18:43 UTC, Menelion commented
@chkas Yes, closing was a mistake. Could you reopen please? If not, I will care of it myself and merge the branch.

2021-11-03 18:48 UTC, chkas commented
It cannot be reopened because the repository has been deleted. I can make a new pull request if that is ok.

2021-11-03 19:11 UTC, chkas commented
I just submitted a new pull request that I will not close.