[GDScript/en] Add GDScript
adambard/learnxinyminutes-docs pull request #4261
Opened 2021-10-31 22:28 UTC by Wichamir

Made a tutorial for Godot's GDScript. Related to #4242
- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

2021-10-31 23:59 UTC, Menelion requested changes
Thanks for your contribution! Please review my suggestions and I'll merge.

2021-10-31 23:59 UTC, Menelion commented on gdscript.html.markdown
> +filename: learn_gdscript.gd
```suggestion
filename: learngdscript.gd
```

2021-10-31 23:59 UTC, Menelion commented on gdscript.html.markdown
> +Python's. It's main advantages are ease of use and tight integration with
```suggestion
Python's. Its main advantages are ease of use and tight integration with
```

2021-10-31 23:59 UTC, Menelion commented on gdscript.html.markdown
> +      print("However you don't neeed to put cases before each value.")
```suggestion
      print("However you don't need to put cases before each value.")
```

2021-10-31 23:59 UTC, Menelion commented on gdscript.html.markdown
> +  var f = float(42) # cast using variables contructor
```suggestion
  var f = float(42) # cast using variables constructor
```

2021-10-31 23:59 UTC, Menelion commented on gdscript.html.markdown
> +# _init gets called when object gets initialized
```suggestion
# _init is called when object gets initialized
```

2021-10-31 23:59 UTC, Menelion commented on gdscript.html.markdown
> +# This is the object's contructor.
```suggestion
# This is the object's constructor.
```

2021-10-31 23:59 UTC, Menelion commented on gdscript.html.markdown
> +# _ready gets called when when script's node and
```suggestion
# _ready gets called when script's node and
```

2021-10-31 23:59 UTC, Menelion commented on gdscript.html.markdown
> +# _physics_process gets called every physics frame.
```suggestion
# _physics_process gets called on every physics frame.
```

2021-10-31 23:59 UTC, Menelion commented on gdscript.html.markdown
> +  var path1 = NodePath("path/to/someting")
```suggestion
  var path1 = NodePath("path/to/something")
```

2021-10-31 23:59 UTC, Menelion commented on gdscript.html.markdown
> +Signal system is Godot's implementation of observer programming
```suggestion
Signal system is Godot's implementation of the observer programming
```

2021-10-31 23:59 UTC, Menelion commented on gdscript.html.markdown
> +const CONSTANT := "Typed contant."
```suggestion
const CONSTANT := "Typed constant."
```

2021-11-01 10:16 UTC, Wichamir commented
Ok, I read through the whole thing again. It turned out I somehow mismatched types in "Accessing other nodes in the scene tree" section and did some other small mistakes there, so I fixed those. I also reviewed your suggestions. Thanks for checking for typos.

2021-11-01 21:12 UTC, Menelion approved these changes
Thank you!

2021-11-01 21:12 UTC, merged