[typescript/en] Add template literal types
adambard/learnxinyminutes-docs pull request #4265
Opened 2021-11-07 22:12 UTC by edazpotato

- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [ ] Yes, I have double-checked quotes and field names!

2021-11-08 22:39 UTC, Menelion requested changes
Thanks! Please fix the typo (you can just commit suggestion) and I'll merge.

2021-11-08 22:39 UTC, Menelion commented on typescript.html.markdown
> +// Use to create complex stirng types
```suggestion
// Use to create complex string types
```

2021-11-09 00:41 UTC, edazpotato commented
Done!

2021-11-09 23:08 UTC, Menelion approved these changes
Thank you!

2021-11-09 23:08 UTC, merged