[python/zh-cn]Complete Translation
adambard/learnxinyminutes-docs pull request #4351
Opened 2022-03-21 04:07 UTC by mapleincode

- [√] I solemnly swear that this is all original content of which I am the original author
- [√] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [√] Pull request touches only one file (or a set of logically related files with similar changes made)
- [√] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [√] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [√] Yes, I have double-checked quotes and field names!

2022-03-21 04:36 UTC, imba-tjd commented on zh-cn/python-cn.html.markdown
> +        # 因此，我们需要显示的调用初始类的 __init___
```suggestion
        # 因此，我们需要显式调用初始类的 __init__
```

2022-03-21 04:38 UTC, imba-tjd commented on zh-cn/python-cn.html.markdown
> +    # 性或方法对 Python 有特殊意义，但是允许用户自行定义。
`属性`放到同一行里吧

2022-03-21 04:43 UTC, imba-tjd commented on zh-cn/python-cn.html.markdown
>  # 传统的变量命名是小写，用下划线分隔单词
```suggestion
# 习惯上变量命名是小写，用下划线分隔单词
```

2022-03-21 04:49 UTC, imba-tjd commented on zh-cn/python-cn.html.markdown
> +# 注意不要把 bool(ints) 与位运算、and/or (&, |) 混淆
```suggestion
# 注意不要把 bool(ints) 与位运算的 "按位与"、"按位或" (&, |) 混淆
```

2022-03-21 04:58 UTC, imba-tjd requested changes
我还建议open()的部分提一下encoding='utf-8'。

另外，markdown的checkbox的语法，`- [ ]`是未勾选，`- [x]`是勾选。不是打√

2022-03-21 04:58 UTC, imba-tjd commented on zh-cn/python-cn.html.markdown
>  3 * 2.0 # => 6.0
现在原文没有这句话了，有的是

```
# The result of division is always a float
10.0 / 3  # => 3.3333333333333335
```

2022-03-21 04:58 UTC, imba-tjd commented on zh-cn/python-cn.html.markdown
> +# 数值与 True 和 False 之间的运算
```suggestion
# 数值与 True 和 False 之间的比较运算
```

2022-03-21 04:58 UTC, imba-tjd commented on zh-cn/python-cn.html.markdown
这里少了一段

```
# if can be used as an expression
# Equivalent of C's '?:' ternary operator
"yay!" if 0 > 1 else "nay!"  # => "nay!"

```

2022-03-21 05:25 UTC, mapleincode commented on zh-cn/python-cn.html.markdown
>  3 * 2.0 # => 6.0
原文是把 `35 / 5 # 7.0` 作为普通案例，我这边把除法和其他三个区分开来。
而且  `35 / 5 # 7.0`  比 `10.0 / 3` 更能提现 `The result of division is always a float`

2022-03-21 05:25 UTC, mapleincode commented on zh-cn/python-cn.html.markdown
>  3 * 2.0 # => 6.0
而 `浮点数的运算结果也是浮点数` 这个是否也可以作为知识点保留？

2022-03-21 06:23 UTC, imba-tjd commented on zh-cn/python-cn.html.markdown
>  3 * 2.0 # => 6.0
行吧

2022-03-21 06:25 UTC, imba-tjd approved these changes
I will wait for a week before merging in order to see whether someone else wants to review.

2022-03-22 01:10 UTC, imba-tjd commented on zh-cn/python-cn.html.markdown
> +    contents = file.read()           # 从文件以 utf-8 的编码读取字符串（默认为 ascii）
默认不是ascii，是win下默认是所谓的*ANSI*，Linux下默认是u8。没必要加在这里，直接给512行后面加一下注释，说win下一般要指定encoding = "utf-8"等等就好了

2022-04-08 12:06 UTC, imba-tjd commented
Thanks for your contribution!

2022-04-08 12:06 UTC, merged