[r/pt-br] Translate R Markdown
adambard/learnxinyminutes-docs pull request #4364
Opened 2022-04-04 00:03 UTC by mribeirodantas

Translation of the markdown file of R to Brazilian Portuguese and update of the header with some information regarding the translator.

- [X] I solemnly swear that this is all original content of which I am the original author
- [X] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [X] Pull request touches only one file (or a set of logically related files with similar changes made)
- [X] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [X] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [X] Yes, I have double-checked quotes and field names!

2022-04-06 14:52 UTC, mribeirodantas commented
I'm not sure how it works in this project, but I think it may help to mention the original authors of the file :-)

@isomorphisms @kalinn @e99n09

2022-06-04 15:12 UTC, halian-vilela requested changes
Fala @mribeirodantas ! 

Tava zapeando por essas cheat-sheets, achei sua tradução ainda em PR, enquanto dava uma lida achei alguns typos e etc, resolvi submeter uma pequena revisão!

Abraços

2022-06-04 15:12 UTC, halian-vilela commented on pt-br/r-pt.html.markdown
> +# A função data.frame() converte vetores de caracteres em vetores de fator
Esse comportamento mudou a partir do R 4.0.0, acho que valeria a pena atualizar.

<img width="934" alt="image" src="https://user-images.githubusercontent.com/1423653/172010330-dae80779-1882-422b-b1a1-6c1192e0e09b.png">

2022-06-04 15:12 UTC, halian-vilela commented on pt-br/r-pt.html.markdown
> +# Arranjos criam tabelas n-dimensionais
```suggestion
# Arranjos (arrays) criam tabelas n-dimensionais
```

2022-06-04 15:12 UTC, halian-vilela commented on pt-br/r-pt.html.markdown
> +write.csv(pets, "pets2.csv") # to make a new .csv file
```suggestion
write.csv(pets, "pets2.csv") # para criar um novo arquivo .csv
```

2022-06-04 17:55 UTC, mribeirodantas commented on pt-br/r-pt.html.markdown
> +# A função data.frame() converte vetores de caracteres em vetores de fator
Concordo. [Fiz isso na época que traduzi o documento original em inglês](https://github.com/adambard/learnxinyminutes-docs/pull/4372), mas infelizmente até hoje não recebi resposta nem ao pull request da versão original em inglês, nem ao pull request da tradução. Acho que o correto é corrigir antes na versão original em inglês, e não na tradução, portanto essa sugestão não será comittada.

2022-06-26 22:16 UTC, merged