[html/ru-ru]: make spellcheck in file
adambard/learnxinyminutes-docs pull request #4369
Opened 2022-04-07 13:59 UTC by de1ayer

- [ ] I solemnly swear that this is all original content of which I am the original author
- [ ] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [ ] Pull request touches only one file (or a set of logically related files with similar changes made)
- [ ] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [ ] Yes, I have double-checked quotes and field names!

2022-04-07 22:27 UTC, Menelion requested changes

2022-04-07 22:27 UTC, Menelion commented on ru-ru/html-ru.html.markdown
> +Это язык используют для написания страниц для World Wide Web (всемирной паутины).
```suggestion
Этот язык используют для написания страниц для World Wide Web (всемирной паутины).
```

2022-04-07 22:27 UTC, Menelion commented on ru-ru/html-ru.html.markdown
> +<!-- Комментарии заключаются как эта линия! -->
Всё равно как-то… кривовато. Может, что-то вроде «комментарии обозначаются, как на этой строке»? или «обрамляются, как эта строка»? Что-нибудь в эту сторону.

2022-04-07 22:27 UTC, Menelion commented on ru-ru/html-ru.html.markdown
> +<!-- HTML-файл всегда начинается с указанием браузеру, что страница - это HTML. -->
```suggestion
<!-- HTML-файл всегда начинается с указания браузеру, что страница — это HTML. -->
```

2022-04-08 08:17 UTC, de1ayer commented on ru-ru/html-ru.html.markdown
> +<!-- Комментарии заключаются как эта линия! -->
Тогда так (я в смысл сильно старался не лезть)
<!-- Это комментарий. -->

2022-04-08 08:18 UTC, de1ayer commented
Обновлено

2024-01-30 10:26 UTC, vendethiel commented on ru-ru/html-ru.html.markdown
> +<!-- Комментарии заключаются как эта линия! -->
@Menelion any comments?

2024-04-03 09:30 UTC, verhovsky commented on ru-ru/html-ru.html.markdown
> +<!-- Комментарии заключаются как эта линия! -->
```suggestion
<!-- Это комментарий. -->
```

2024-04-03 09:31 UTC, merged