[dart/pt-br] More natural language
adambard/learnxinyminutes-docs pull request #4515
Opened 2022-10-12 00:07 UTC by insign

- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

2022-10-12 09:08 UTC, mribeirodantas requested changes

2022-10-13 13:41 UTC, insign commented
Ficou melhor ainda

2022-10-13 17:00 UTC, mribeirodantas commented
Show! Faz a alteração que dou o merge aqui 😄

2022-10-13 18:04 UTC, insign commented
Pronto, mas BTW, acho que tá super defasado o código pois entre outras coisas "new" é desencorajado. Infelizmente estou sem tempo pra atualizar...

2022-10-14 07:47 UTC, mribeirodantas commented
Super entendo, @insign. Por hora, você poderia abrir um issue com as informações/detalhes que você acha que poderiam ser melhoradas? Daí é torcer para alguém habilitado e com tempo aparecer para submeter um pull request 😄

2022-10-14 07:47 UTC, mribeirodantas approved these changes

2022-10-14 07:48 UTC, merged