[processing/pt_br] Adds processing translation to pt_br
adambard/learnxinyminutes-docs pull request #4527
Opened 2022-10-27 20:10 UTC by kemelzaidan

- [X] I solemnly swear that this is all original content of which I am the original author
- [X] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [X] Pull request touches only one file (or a set of logically related files with similar changes made)
- [X] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [X] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [X] Yes, I have double-checked quotes and field names!

2022-10-28 01:29 UTC, mribeirodantas requested changes
There are many small mistakes, such as translating the name of the language by accident(?). I skimmed over the translation but it'd be great if you can review your translation to make sure no other mistakes passed.

Thanks for the contribution!

2022-10-28 01:29 UTC, mribeirodantas commented on pt-br/processing-pt.html.markdown
> +	- ["Kemel Zaidan", "https://github.com/kemelzaidan"]
```suggestion
    - ["Kemel Zaidan", "https://github.com/kemelzaidan"]
```

2022-10-28 01:29 UTC, mribeirodantas commented on pt-br/processing-pt.html.markdown
> +A linguagem é tipada estaticamente e também vem com a sua IDE oficial para
```suggestion
A linguagem é tipada estaticamente e também vem com o seu Ambiente de Desenvolvimento Integrado (do inglês Integrated Development Environment - IDE) oficial para
```

2022-10-28 01:29 UTC, mribeirodantas commented on pt-br/processing-pt.html.markdown
> +  println("Olá Mundo!"); // Outra linguagem cilada para ponto e vírgula, não é?
I think this is not a good translation (the original one has a typo also, so it doesn't help). One suggestion (but feel free to fix to some other wording if you want):

```suggestion
  println("Olá Mundo!"); // Mais uma linguagem com esse maldito ponto e vírgula, não é?
```

2022-10-28 01:29 UTC, mribeirodantas commented on pt-br/processing-pt.html.markdown
> +O processamento é fácil de aprender e é particularmente útil para criar
```suggestion
A linguagem processing é fácil de aprender e é particularmente útil para criar
```

2022-10-28 01:29 UTC, mribeirodantas commented on pt-br/processing-pt.html.markdown
> +// O processamento fornece duas implementações de curvas; usando curve() e
```suggestion
// O processing fornece duas implementações de curvas; usando curve() e 
```

2022-10-28 01:29 UTC, mribeirodantas commented on pt-br/processing-pt.html.markdown
> +filter(sombreador); // O processamento suporta várias funções de filtro para manipulação de imagens.
```suggestion
filter(sombreador); // O processing suporta várias funções de filtro para manipulação de imagens.
```

2022-10-28 01:29 UTC, mribeirodantas commented on pt-br/processing-pt.html.markdown
> +e até mesmo suas próprias aulas. (Confie em mim! O processamento de projetos pode ficar realmente monstruoso...)
```suggestion
e até mesmo suas próprias aulas. (Confie em mim! Projetos com processing podem ficar realmente monstruosos...)
```

2022-11-16 14:40 UTC, kemelzaidan commented on pt-br/processing-pt.html.markdown
> +// O processamento também suporta operações trigonométricas fornecendo um
Processing should start in capital letter, since it refers to the language name. Fixed in another commit

2022-11-16 14:42 UTC, kemelzaidan reviewed
Committing proposed fixes

2022-11-20 06:44 UTC, mribeirodantas approved these changes

2022-11-20 06:44 UTC, merged