[pcre/fr] PCRE French translation
adambard/learnxinyminutes-docs pull request #4897
Opened 2024-04-17 06:59 UTC by Th3G33k

- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [ ] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [ ] Yes, I have double-checked quotes and field names!

Added French translation for PCRE

2024-04-18 07:57 UTC, vendethiel commented on fr-fr/pcre-fr.html.markdown
> +Une expression régulière (regex ou regexp en abrégé) est une chaîne de texte spéciale pour décrire un masque de recherche. Par exemple, pour extraire le nom de domaine d'une chaîne, nous pouvons dire
c'est le protocole, pas le nom de domaine

2024-04-18 08:01 UTC, vendethiel requested changes

2024-04-18 08:01 UTC, vendethiel commented on fr-fr/pcre-fr.html.markdown
> +  \D     tout chiffre non décimal
tout sauf un chiffre décimal*

2024-04-18 08:01 UTC, vendethiel commented on fr-fr/pcre-fr.html.markdown
> +  \W     tout caractère, ne pouvant pas former un mot
pas de `,` sur les exclusions

2024-04-18 08:01 UTC, vendethiel commented on fr-fr/pcre-fr.html.markdown
> + It is a standard Apache access log.
Non traduit

2024-04-20 05:51 UTC, Th3G33k commented
I applied the suggestions, thank you @vendethiel

2024-04-20 10:52 UTC, vendethiel approved these changes

2024-04-20 10:52 UTC, vendethiel commented
Merci !

2024-04-20 10:52 UTC, merged