[sql/en] More examples
adambard/learnxinyminutes-docs pull request #4898
Opened 2024-04-17 09:59 UTC by Th3G33k

- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [ ] Yes, I have double-checked quotes and field names!

Add more inline code examples, that might be useful :
- multiline comments /* */
- ORDER BY ASC / DESC
- AS
- IN, NOT IN, BETWEEN, AND, OR
- GROUP BY, HAVING
- UNION

2024-04-17 10:04 UTC, vendethiel requested changes

2024-04-17 10:04 UTC, vendethiel commented on sql.html.markdown
> +-- from a set of values. Most commonly used functions are :
no space before `:`

2024-04-17 10:04 UTC, vendethiel commented on sql.html.markdown
> +-- Use HAVING to filter rows using aggregated values.
using => by

2024-04-17 10:04 UTC, vendethiel commented on sql.html.markdown
> +-- SQL syntax order is :
no space before `:`

2024-04-19 08:41 UTC, verhovsky commented on sql.html.markdown
> +-- Aliases, using the optional keyword AS, can be used for column / table names.
```suggestion
-- Aliases, using the optional keyword AS, can be used for column/table names.
```

2024-04-19 08:43 UTC, Th3G33k commented
Thanks @vendethiel for the review. I applied the suggestions

2024-04-19 08:51 UTC, vendethiel approved these changes

2024-04-19 08:51 UTC, verhovsky commented on sql.html.markdown
> +
```suggestion
```

2024-04-19 08:52 UTC, merged