[bc/zh-cn] Add Simplified Chinese Translation of `bc`
adambard/learnxinyminutes-docs pull request #4977
Opened 2024-06-10 02:38 UTC by CloneWith

- [x] I solemnly swear that this is all original content of which I am the original author
- [x] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x] Pull request touches only one file (or a set of logically related files with similar changes made)
- [x] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
  - [x] Yes, I have double-checked quotes and field names!

2024-06-10 04:54 UTC, geoffliu requested changes
@CloneWith 感谢！有几个地方的翻译是从英文直译，感觉有些生硬。我提了建议，麻烦看一下？

2024-06-10 04:54 UTC, geoffliu commented on zh-cn/bc-cn.html.markdown
> +/*这是本地变量的示例：*/
局部变量

2024-06-10 04:54 UTC, geoffliu commented on zh-cn/bc-cn.html.markdown
> +a = (num) && (1) || (0) /*&& 代表“和”，|| 代表“或”*/
s/和/与/

2024-06-10 04:54 UTC, geoffliu commented on zh-cn/bc-cn.html.markdown
> +    \t: 换挡符
制表符

2024-06-10 04:54 UTC, geoffliu commented on zh-cn/bc-cn.html.markdown
> +    \n: 新行
换行符

2024-06-10 04:54 UTC, geoffliu commented on zh-cn/bc-cn.html.markdown
> +    并且你无法直接存储字符串常量。*/
并且 bc 不支持直接存储字符串常量

2024-06-10 04:54 UTC, geoffliu commented on zh-cn/bc-cn.html.markdown
> +    添加一个英文分号，也可以不加。*/
每个语句后可以添加一个英文分号，也可以不加。

2024-06-10 04:54 UTC, geoffliu commented on zh-cn/bc-cn.html.markdown
> +    可用转义序列表的简化版：
以下为 bc 中常用转义序列表

2024-06-10 07:30 UTC, imba-tjd approved these changes

2024-06-11 03:58 UTC, geoffliu approved these changes

2024-06-11 03:58 UTC, merged